# Config file for iProtector v4.0 by Kevin Andrews;
# Forked from the original LDX-MCPE/iProtector repository, implementing messages support
# and PocketMine-MP API 3.0.0 compatiblity

# Messages for protected areas:
Messages:

 # No permission to place that block
 Place: 'You do not have permission to place your {block}!'
 
 # No permission to break that block
 Break: 'You do not have permission to break my {block}!'
 
 # No permission to touch that block or activate things like chests
 Touch: 'You do not have permission to touch my {block}!'
 
# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt?
  God: false

  # Keep players from editing the world?
  Edit: false

  # Keep players from touching blocks and activating things like chests?
  Touch: false

# Settings for unprotected areas in individual worlds:
Worlds:

  DEFAULT:

    # Keep players from getting hurt?
    God: false

    # Keep players from editing the world?
    Edit: false

    # Keep players from touching blocks and activating things like chests?
    Touch: false
